baseURL = "https://oreshika.github.io"
title = "oreshika-blog"
theme = "axiom"
languageCode = "ja"
defaultContentLanguage = "ja"
hasCJKLanguage = true
publishDir = "docs"
[params]
mainSections = ["posts"]
